db_password = "6Firegate!"

GPT_API_KEY = "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"
