[oauth]
client_id = "RwSgFKlC8qd6eKaqZLLqzvWxaRldJ601"
client_secret = "A2yTgCnr3X2bDAzqWJMwurH67xKqytTZF3zc2iuXNXyS4pvlY5vHfmwzYx8fU-vt"
authorization_url = "https://provider.com/oauth/authorize"
token_url = "https://provider.com/oauth/token"
redirect_uri = "http://localhost:8501"
scope = "read write"
#state = "random-string-for-security"  # Optional, used for CSRF protection
